// packages/admin-ui/svelte/src/components/Table.svelte
<!--
Copyright (C) 2023-2026 Chaos
This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License.
-->
<script lang="ts">
  import { onMount } from 'svelte'
  import { registerAdminElements } from '@chaos_team/admin-ui-core/register'

  export let loading = false
  export let empty = false
  export let loadingLabel = 'Loading...'
  export let emptyLabel = 'No data available.'
  onMount(() => registerAdminElements())
</script>

<aui-table {loading} {empty} {loadingLabel} {emptyLabel}><slot /></aui-table>

// web/src/components/ui/table.tsx
/*
Copyright (C) 2023-2026 Chaos

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program. If not, see <https://www.gnu.org/licenses/>.

*/
export {
  Table,
  TableBody,
  TableCaption,
  TableCell,
  TableFooter,
  TableHead,
  TableHeader,
  TableRow,
} from '@chaos_team/chaos-ui/ui'
